#################################################################################################
#parole che deteminano la features semantica
#################################################################################################
lista.parole<-list()
lista.parole$parole.cronaca<-c("cronaca","yara", "processo", "allagamenti","scampia","omicidio", "giglio","carcere","camorra","mafia", "bossetti", "naufragio", "esondazione", "nubifragio", "prostituzione","droga", "ndrangheta", "corruzione")
lista.parole$parole.mondo<-c("gaza", "israele","raid", "iraq", "hamas", "obama", "merkel", "nassiriya","afghanistan","libia","clinton", "putin","internazionale", "isrealiani", "isis", "attentato")
lista.parole$parole.politica<-c("politica", "renzi", "berlusconi","ruby", "elezioni", "senato", "repubblica","governo", "bunga", "grillo", "m5s", "riforma","riforme","ministri","sindaco","elettorale","migranti", "minetti", "parlamento")
lista.parole$parole.economia<-c("economia","bce", "fed", "alitalia","esuberi", "sciopero", "spread", "economico", "pil", "dollaro", "inps", "eurozona", "eurogruppo")
lista.parole$parole.previsioni_we <-c("sab","dom")
lista.parole$parole.previsioniNord <-c("piemonte","aosta","lombardia","veneto","friuli","trentino","adige","emilia","liguria")
lista.parole$parole.previsioniCentro <-c("toscana","umbria","lazio","marche","friuli","trentino","adige","emilia")
lista.parole$parole.previsioniSud <-c("campania","basilicata","puglia","molise","calabria","sicilia","sardegna")
lista.parole$parole.previsioni_villeggiatura<-c("montagna","mare")
lista.parole$parole.calcio<-c("calcio","calciomercato","champions","gol","fantascudetto","inter", "milan","juventus","calciatori","juve","Calciomercato","balotelli","bayern","sampdoria","bundesliga","mourinho", "ibrahimovic","totti","atalanta","kaka","goleador","hellas", "milanello", "fifa")
lista.parole$parole.formula1<-c("formula","motori","ferrari","vettel","alonso","silverstone","hamilton","schumacher")
lista.parole$parole.motogp<-c("motogp","motori","moto","motomondiale")
lista.parole$parole.ciclismo<-c("ciclismo","tour","france","tappa")
lista.parole$parole.basket<-c("nba","basket","lakers", "bulls")
lista.parole$parole.tennis<-c("tennis", "wimbledon")
lista.parole$parole.altrisport<-c("olimpiadi","rugby","nuoto","pallanuoto","volley","scherma","golf", "baseball")
lista.parole$parole.fantagiochi<-c("fantascudetto","fantamondiale","fantacampioni","fantagp")
lista.parole$parole.programmitv<-c("skyuno","masterchef","xfactor","hellskitchen","juniormasterchef", "theapprentice", "apprentice")
lista.parole$parole.cinema<-c("cinema","film","commedia","drammatico","thriller","horror", "oscar", "trameFilm")
lista.parole$parole.gossip <-c("mag","gossip","sexy","style","modelle", "spettacolo","festival","concerto","middelton","armani","bullock", "beyonce", "arcuri", "bieber", "playboy")
lista.parole$parole.problemi_tecnici<-c("decoder","abbonamento","mysky","demand", "installazione", "multivision", "contratto", "disdetta", "skygo", "skylink")
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#